# Generated by Django 5.2.7 on 2025-12-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appjudc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionArticuloCientifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_conocimiento', models.CharField(max_length=100, verbose_name='Área de Conocimiento')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoría')),
                ('carrera', models.CharField(max_length=200, verbose_name='Carrera')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título de la investigación')),
                ('autores', models.TextField(verbose_name='Autores')),
                ('criterio1_planteamiento', models.IntegerField(verbose_name='Planteamiento del problema')),
                ('criterio2_objetivos', models.IntegerField(verbose_name='Objetivos de investigación')),
                ('criterio3_marco_teorico', models.IntegerField(verbose_name='Marco teórico y antecedentes')),
                ('criterio4_metodologia', models.IntegerField(verbose_name='Calidad metodológica')),
                ('criterio5_analisis', models.IntegerField(verbose_name='Análisis y discusión')),
                ('criterio6_conclusiones', models.IntegerField(verbose_name='Conclusiones y recomendaciones')),
                ('criterio7_presentacion', models.IntegerField(verbose_name='Presentación de resultados')),
                ('puntuacion_total', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Puntuación Total')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje')),
                ('evaluador', models.CharField(max_length=200, verbose_name='Nombre del evaluador')),
                ('firma', models.CharField(blank=True, max_length=200, null=True, verbose_name='Firma')),
                ('fecha_evaluacion', models.DateField(verbose_name='Fecha de evaluación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Evaluación de Artículo Científico',
                'verbose_name_plural': 'Evaluaciones de Artículos Científicos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnet', models.CharField()),
            ],
        ),
    ]
