# Generated by Django 5.2.7 on 2025-12-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appjudc', '0002_evaluacionarticulocientifico_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_docente', models.CharField(max_length=20, unique=True, verbose_name='Código del Docente')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Docente')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('especialidad', models.CharField(max_length=200, verbose_name='Especialidad')),
                ('area_conocimiento', models.CharField(choices=[('1', 'Departamento de Ciencias y Tecnología'), ('2', 'Departamento de Ciencias Economicas y Administrativas'), ('3', 'Departamento de Educación y Humanidades')], max_length=1, verbose_name='Área de Conocimiento')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['nombre'],
            },
        ),
    ]
