# Generated by Django 5.2.7 on 2025-12-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appjudc', '0003_docente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='id',
        ),
        migrations.AlterField(
            model_name='docente',
            name='codigo_docente',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Código del Docente'),
        ),
    ]
