# Generated by Django 5.2.7 on 2025-12-10 20:23

import django.db.models.deletion
from django.db import migrations, models


import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('appjudc', '0004_delete_usuario_remove_docente_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConocimiento',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Codigo del Area de Conocimiento')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Area de Conocimiento')),
            ],
            options={
                'verbose_name': 'Area de Conocimiento',
                'verbose_name_plural': 'Areas de Conocimiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['nombre', 'apellido'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AddField(
            model_name='estudiante',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(max_length=30, verbose_name='Apellido del Estudiante'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='carnet',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Numero de Carnet'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre del Estudiante'),
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Codigo de la Carrera')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Carrera')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('area_conocimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='appjudc.areaconocimiento', verbose_name='Área de Conocimiento')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='appjudc.carrera', verbose_name='Carrera'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['nombre', 'apellido'], name='appjudc_est_nombre_f47091_idx'),
        ),
        migrations.AddIndex(
            model_name='carrera',
            index=models.Index(fields=['nombre'], name='appjudc_car_nombre_74a75c_idx'),
        ),
    ]
