# Generated by Django 5.2.7 on 2025-12-10 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appjudc', '0005_areaconocimiento_alter_estudiante_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='apellido',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido del Docente'),
        ),
        migrations.AddField(
            model_name='docente',
            name='codigo_inss',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Código INSS'),
        ),
        migrations.AddField(
            model_name='docente',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='docente',
            name='tipo_contrato',
            field=models.CharField(choices=[('TC', 'Tiempo completo'), ('MP', 'Medio tiempo'), ('HC', 'Horas Contratadas')], default='TC', max_length=2, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='codigo_docente',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código del Docente'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='appjudc.carrera', verbose_name='Carrera'),
        ),
    ]
