# Generated by Django 5.2.7 on 2025-12-10 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appjudc', '0006_docente_apellido_docente_codigo_inss_docente_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='carrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='appjudc.carrera', verbose_name='Carrera'),
        ),
    ]
