# Generated by Django 5.2.7 on 2025-12-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appjudc', '0007_alter_estudiante_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionarticulocientifico',
            name='autores1',
            field=models.CharField(default=-2018, max_length=200, verbose_name='Autor 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionarticulocientifico',
            name='autores2',
            field=models.CharField(default=0.0006995884773662552, max_length=200, verbose_name='Autor 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionarticulocientifico',
            name='autores3',
            field=models.CharField(default=17, max_length=200, verbose_name='Autor 3'),
            preserve_default=False,
        ),
    ]
