# Generated by Django 5.2.7 on 2025-12-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appjudc', '0008_evaluacionarticulocientifico_autores1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacionarticulocientifico',
            name='autores3',
        ),
    ]
