# Generated by Django 5.2.7 on 2025-12-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appjudc', '0009_remove_evaluacionarticulocientifico_autores3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionarticulocientifico',
            name='autores',
            field=models.TextField(max_length=100, verbose_name='Autor 1'),
        ),
        migrations.AlterField(
            model_name='evaluacionarticulocientifico',
            name='autores1',
            field=models.CharField(max_length=100, verbose_name='Autor 2'),
        ),
        migrations.AlterField(
            model_name='evaluacionarticulocientifico',
            name='autores2',
            field=models.CharField(max_length=100, verbose_name='Autor 3'),
        ),
    ]
